#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
eval $(hub alias -s)

export GOPATH=~/go
export PATH=$GOPATH/bin:$PATH

#export IOJSPATH=~/apps/iojs-v1.4.1-linux-x64/
#export PATH=$IOJSPATH/bin:$PATH

export PATH=~/.npm/bin:$PATH

alias vi=vim
alias view='vim -R'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit
prompt agnoster

export EDITOR=vi

# added by travis gem
[ -f /home/jdyson/.travis/travis.sh ] && source /home/jdyson/.travis/travis.sh

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/home/jdyson/.gvm/bin/gvm-init.sh" ]] && source "/home/jdyson/.gvm/bin/gvm-init.sh"

export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
