#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
eval $(hub alias -s)

export GOPATH=~/go
export PATH=$GOPATH/bin:$PATH

#export IOJSPATH=~/apps/iojs-v1.4.1-linux-x64/
#export PATH=$IOJSPATH/bin:$PATH

export PATH=~/.npm/bin:$PATH

alias vi=vim
alias view='vim -R'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit
prompt agnoster

export EDITOR=vim

# added by travis gem
[ -f /home/jdyson/.travis/travis.sh ] && source /home/jdyson/.travis/travis.sh

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/home/jdyson/.gvm/bin/gvm-init.sh" ]] && source "/home/jdyson/.gvm/bin/gvm-init.sh"

export NVM_DIR="/home/jdyson/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
source /home/jdyson/.gulp-autocompletion-zsh/gulp-autocompletion.zsh

bindkey '^R' history-incremental-pattern-search-backward

# The next line updates PATH for the Google Cloud SDK.
source '/home/jdyson/apps/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
source '/home/jdyson/apps/google-cloud-sdk/completion.zsh.inc'
